### ISSUE TITLE
Assert License & copyright on the Arch Guide

### ISSUE THREAD

**Issue by Uniminin** [MajorGamerJay/majorgamerjay.github.io#3]
The [archlinux-install-guide.html](https://majorgamerjay.github.io/content/archlinux-install-guide.html) on your website hosted on github **borrows/contains** a lot of information from my original guide (Upstream: [Uniminin/archlinux-install-guide](https://github.com/Uniminin/archlinux-install-guide)) which is licensed under the terms of [GNU General Public License v3.0](https://github.com/Uniminin/archlinux-install-guide/blob/main/LICENSE) which states the following conditions:
- License and copyright notice
- Same license

None of them were followed or provided. I hope you'll take a wise step afterwards, else I'll have to file a [DMCA](https://github.com/contact/dmca) takedown.

**Comment by Uniminin** [comment]
When you make a creative work (such as writing, graphics, or code), that work is under exclusive copyright by default. That is, the law assumes that as the author of your work, you have a say in what others can do with it.

**Comment by MajorGamerJay** [comment]
ye sure alright no worries

**Comment by MajorGamerJay** [comment]
fixing it

**Comment by Uniminin** [comment]
However, because the author expects that others will use, modify, and share the work. But because the legal default is still exclusive copyright, you need a license that explicitly states these permissions.
